[CH #57710] Interactivity popups
CartoDB/toolkit pull request #113
Opened 2020-05-18 07:19 UTC by manmorjim

### Changes

- Fixes issue: sometimes the feature cannot be clicked

- Fixes issue: Cannot disable hovers

- Add cursor pointer when the mouse is on a feature

- Add Airship popup component as Popup style

- Improves examples: Examples similar to VL: https://carto.com/developers/carto-vl/examples/#example-add-pop-ups-on-click
  - Feature hover
  - Feature click
  - Add pop-ups on hover
  - Add pop-ups on click
  - Interactive based styling

- Fixes issue: event error if layer was not added to the map

2020-05-18 08:55 UTC, VictorVelarde commented on examples/visualization/interactions/add-popups-onclick.html
> +      href="https://libs.cartocdn.com/airship-style/v2.1.1/airship.css"
We can point to minor, and get patches for free, if we use a url like:
https://libs.cartocdn.com/airship-style/v2.1/airship.css (it also works with https://libs.cartocdn.com/airship-style/v2/airship.css)

2020-05-18 12:27 UTC, VictorVelarde commented on examples/visualization/interactions/add-popups-onclick.html
> +      href="https://libs.cartocdn.com/airship-style/v2.1.1/airship.css"
... and the last one is 2.3

2020-05-19 16:07 UTC, alasarr requested changes
It looks great and it works great! Congrats on the nice work.

As an improvement, I feel that Layer.ts is growing too much. Could you try to move some logic of popup to an external module? 

Something like LayerInteration.ts where you can encapsulate all the code related to the layer and the interactivity, so you can define there the code of layer.on, _setPopupHandler, setPopupHover, setPopupClick, _wrapInteractiveStyle

2020-05-20 10:47 UTC, VictorVelarde commented on examples/interactivity/add-popups-onclick.html
> +      href="https://carto.com/developers/carto-vl/v1.4.4/examples/maps/style.css"
We should remove this. At the very end, it's equivalent to our map 100% custom style

2020-05-20 10:47 UTC, VictorVelarde commented on examples/interactivity/add-popups-onclick.html
> +    <title>GeoJSON Layer with CARTO Tiles Example</title>
Not urgent, but we should update titles too

2020-05-20 10:48 UTC, VictorVelarde commented on examples/interactivity/add-popups-onclick.html
> +      }
This is ok for now. I will try to update the styles for examples in the near future, to use airship all around (so styling is homogeneous with popups)

2020-05-20 10:53 UTC, VictorVelarde commented on examples/interactivity/add-popups-onhover.html
> +        window.deckMap = deckMap;
I would remove the window.deckMap. This is nice for debugging, but we should try to be homogenous on examples. These examples will be a very relevant part of the documentation!

2020-05-20 17:02 UTC, VictorVelarde commented on packages/viz/src/lib/layer/Layer.ts
> +  private _interacitivity: LayerInteractivity;
👀 typo: `_interacitivity`

2020-05-20 17:04 UTC, VictorVelarde commented on packages/viz/src/lib/layer/Layer.ts
> +    );
How about a small refactor, having a helper method to do `this._interactivity = buildInteractivity(options)`?

2020-05-21 08:24 UTC, VictorVelarde commented on packages/viz/src/lib/layer/Layer.ts
> +      ...this._interacitivity.getDefaultOptions(),
typo here

2020-05-21 17:20 UTC, alasarr commented on packages/viz/src/lib/layer/Layer.ts
> +    this._interactivity.setPopupClick(elements);
Vamos!! 👌

2020-05-21 17:28 UTC, alasarr approved these changes

2020-05-21 17:28 UTC, merged